### ISSUE TITLE
Ruff v0.5.0 deprecated `ruff <path>` in favor of `ruff check <path>`

### ISSUE THREAD

**Issue by sneakers-the-rat** [koxudaxi/ruff-pycharm-plugin#467] opened 2024-07-08 23:30 UTC
**Describe the bug**
PyCharm raises an IDE error from the plugin:

```
Caused by: The following command was executed:

/Users/jonny/git/p2p-ld/nwb-linkml/.venv/bin/ruff --exit-zero --no-cache --force-exclude --no-fix --output-format json -

The exit code: 1
The error output of the command:


error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```

**To Reproduce**

1. Have installed ruff `>=0.5.0` 
2. use tool as normal

**Expected behavior**
To not error on the ruff call :)

**Environments (please complete the following information):**
 - IDE: PyCharm Pro 2023.2.1
 - OS: macOS 14.3.1
 - Ruff Version: 0.5.0
 - Plugin version: 0.0.27

**Comment by pySilver** [comment] 2024-08-09 19:22
@koxudaxi any chance you can look at this?

**Comment by sneakers-the-rat** [comment] 2024-08-09 23:14
I noticed that there were a bunch of updates to this plugin that I wasnt able to grab on pycharm, and it turns out pycharm just silently refuses the updates if its an older version than can support the plugin versions. Updated pycharm, and the new versions dont have this problem :)

**Comment by koxudaxi** [comment] 2024-08-10 00:00
@sneakers-the-rat @pySilver 
yes, the issue is resolved in the PR. https://github.com/koxudaxi/ruff-pycharm-plugin/pull/405

The plugin's latest version supports only the latest PyCharm version. 
Could you Please upgrade the PyCharm version and upgrade ruff plugin?

**Comment by pySilver** [comment] 2024-08-10 00:02
@koxudaxi oh great! am I safe to upgrade to the latest ruff (0.5.7) too?

**Comment by pySilver** [comment] 2024-08-10 00:34
@koxudaxi unfortunately latest pycharm is not supported

![CleanShot 2024-08-10 at 02 34 18](https://github.com/user-attachments/assets/7ce2261e-6d23-4a6d-84bf-12ac1846fdeb)

**Comment by pySilver** [comment] 2024-08-10 00:36
Ach, I need an EAP for that :)

**Comment by koxudaxi** [comment] 2024-08-10 01:08
@pySilver 
We don't need to use [0.0.35](https://plugins.jetbrains.com/plugin/20574-ruff/versions/stable/576733)
you should use 0.0.34
The difference between 0.0.34  and 0.0.35 is only for supporting the latest EAP.
https://plugins.jetbrains.com/plugin/20574-ruff/versions

**Comment by sneakers-the-rat** [comment] 2024-08-10 03:10
(this can probably get closed, hopefully? thx for fixing <3)

**Closed** 2024-08-15 02:29 UTC
