### ISSUE TITLE
File specific rule not getting applied

### ISSUE THREAD

**Issue by fenilgmehta** [koxudaxi/ruff-pycharm-plugin#277] opened 2023-10-02 11:17 UTC
Hi team, thanks for this awesome plugin 🙏

**Describe the bug**
The plugin is not taking into account `[per-file-ignores]`

**To Reproduce**
1. Create a ruff file like below (name it `ruff.toml`
```toml
# Enable this list of rules.
select = [
    "S",  # flake8-bandit
]
ignore = []
target-version = "py311"

# Rules to Ignore for matching files.
[per-file-ignores]
# "test files" (i.e. unit tests)
"test_*.py" = [
    "S101",  # Use of assert detected
    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    "SLF001",  # Private member accessed: {access}
]
```
2. Create python file and name it `test_ruff_rule_in_pycharm.py`
```python
def test_something() -> None:
    """Ruff will highlight the below assert in PyCharm."""
    assert True
```

**Expected behavior**
The `assert` in `test_ruff_rule_in_pycharm.py` should **NOT** be highlighted like the one shown in `Screenshots` section. CLI works perfectly fine.

**Screenshots**
![Screenshot_20231002_164541](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/42742240/0d7fe304-2346-43ed-a51f-ad98b9f6a60a)

**Environments**
 - IDE: PyCharm 2023.2.1 (Professional Edition)
 - OS: Fedora Linux 35
 - Ruff Version 0.0.290
 - Plugin version 0.0.20

**Comment by koxudaxi** [comment] 2023-10-13 17:17
@fenilgmehta 
Thank you for reporting the issue.
Unfortunately, I can't reproduce the problem.
Would you happen to have the additional information to find the root cause?

Other users have shared similar problems, but I can't reproduce them in my environment. https://github.com/koxudaxi/ruff-pycharm-plugin/issues/291

![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/630670/83b962f4-262a-472b-bc81-f85351f9068b)

**Comment by koxudaxi** [comment] 2024-03-24 16:30
https://github.com/koxudaxi/ruff-pycharm-plugin/issues/291

This is a duplicate of this one and will be closed.

**Closed by koxudaxi** 2024-03-24 16:30 UTC
